### ISSUE TITLE
error after changing PID

### ISSUE THREAD

**Issue by PHA-SYSOPS** [Phala-Network/runtime-bridge#46]
"name":"prb","hostname":"lifecycle","pid":18,"level":50,"err":{"message":"Cannot read property 'runtime' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'runtime' of undefined\n    at file:///opt/app/src/lifecycle/handlers/lifecycle.js:4:49\n    at Array.map (<anonymous>)\n    at getWorkerStates (file:///opt/app/src/lifecycle/handlers/lifecycle.js:2:7)\n    at queryWorkerState (file:///opt/app/src/lifecycle/handlers/lifecycle.js:21:19)\n    at file:///opt/app/src/lifecycle/handlers/index.js:11:5\n    at Object.queryCallback (file:///opt/app/src/message/index.js:167:25)\n    at Object.dispatch (file:///opt/app/src/lifecycle/rpc.js:27:26)\n    at Redis.<anonymous> (file:///opt/app/src/message/index.js:120:22)\n    at Redis.emit (events.js:400:28)\n    at DataHandler.handleSubscriberReply (/opt/app/node_modules/.pnpm/ioredis@4.27.7/node_modules/ioredis/built/DataHandler.js:82:28)"},"msg":"Cannot read property 'runtime' of undefined","time":"2021-08-15T20:09:11.561Z","v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"from":1,"to":4,"createdAt":1629058151561,"nonce":"6e3949c1-4279-46f7-89b5-00892a85a610","nonceRef":"9b2d3cec-5063-497e-97b9-d579da929115","type":2,"content":{"error":{"extra":"Cannot read property 'runtime' of undefined"},"to":4,"nonceRef":"9b2d3cec-5063-497e-97b9-d579da929115","type":2},"msg":"published to rpc.","time":"2021-08-15T20:09:11.562Z","v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"from":"MTG_MANAGER","to":"MTG_APP","content":{"error":{"extra":"Cannot read property 'runtime' of undefined"}},"createdAt":"1629058151561","nonce":"6e3949c1-4279-46f7-89b5-00892a85a610","nonceRef":"9b2d3cec-5063-497e-97b9-d579da929115","type":"MTP_REPLY","msg":"Receiving...","time":"2021-08-15T20:09:11.562Z","v":0}

**Comment by PHA-SYSOPS** [comment]
to clarify, the GUI does not check if the PID exists, it should
